IO_BLOCK_SLEEP_TIME = 0.05
IO_READ_TIMEOUT = 10

LED_STATUS_PIN = 2

LED_TM1637_ENABLE = False
LED_TM1637_PIN_CLK = 5
LED_TM1637_PIN_DIO = 4

REBOOT_PIN = 32

MOTOR_ENABLE = True
MOTOR_MODEL = "mg996r"
MOTOR_PIN = 12
MOTOR_PWM_FREQ = 1000
MOTOR_PWM_DUTY = 50

FINGER_ENABLE = True
FINGER_MODEL = "as608"
FINGER_WAK_IRQ_ENABLE = True
FINGER_WAK_PIN = 4
FINGER_UART_PORT = "COM3"

BEEP_OUTSIDE_PIN = 13
BEEP_INSIDE_PIN = 14