IO_BLOCK_SLEEP_TIME = 0.05
IO_READ_TIMEOUT = 5

LED_STATUS_PIN = 2

LED_TM1637_ENABLE = False
LED_TM1637_PIN_CLK = 5
LED_TM1637_PIN_DIO = 4

REBOOT_PIN = 32

DOOR_MOTOR_ENABLE = True
DOOR_MOTOR_MODEL = "mg996r"
DOOR_MOTOR_PIN = 12
# Frequency of the PWM signal in Hz
DOOR_MOTOR_PWM_OPEN_FREQ = 50
# Duty: 0-1023
DOOR_MOTOR_PWM_OPEN_DUTY = 26
DOOR_MOTOR_PWM_CLOSE_FREQ = 50
DOOR_MOTOR_PWM_CLOSE_DUTY = 128

# True for steering gear, False for motors
DOOR_MOTOR_KEEP_SIGNAL = True
# Only used if DOOR_MOTOR_KEEP_SIGNAL is False
DOOR_MOTOR_ROLLTATE_DELAY = 1500
# NOTE: Hardware PWM on micropython is buggy if we use micropython 1.18

# Direct Door Controller
DOOR_DIRECT_ENABLE = False
DOOR_DIRECT_PIN_OPEN = 0
DOOR_DIRECT_PIN_CLOSE = 0
DOOR_DIRECT_ROLLTATE_DELAY = 0.5

DOOR_AUTOCLOSE_DELAY = 4000
DOOR_FORCE_LOCK_PIN = 23
DOOR_FORCE_LOCK_STATUS_LED_PIN = 27

WLAN_ALERT_LED_PIN = 26
DOOR_ALERT_LED_PIN = 25

FINGER_ENABLE = True
FINGER_MODEL = "as608"
FINGER_WAK_IRQ_ENABLE = True
FINGER_WAK_PIN = 4
FINGER_UART_PORT = "COM3"
FINGER_SECURITY_LEVEL = 5
FINGER_STATUS_PIN = 2

BEEP_OUTSIDE_PIN = 33
BEEP_INSIDE_PIN = 14

HUMAN_SENSOR_ENABLE = True
HUMAN_SENSOR_PIN = 5
HUMAN_SENSOR_ALERT_WHEN_DETECTED = True