WECHAT_ENABLE = False
WECHAT_CORPID = ""
WECHAT_CORPSECRET = ""
WECHAT_AGENTID = ""
WECHAT_OPEN_DOOR_MESSAGE_ENABLE = True
WECHAT_OPEN_DOOR_MESSAGE_CONTENT = "门已打开\r\n时间：%s\r\n开门方法：%s\r\n操作员：%s\r\n备注：%s"